module.exports = {
  apps: [
    {
      name: "nicopush",
      script: "src/cmd/nicopush.py",
      interpreter: ".venv/bin/python",
      interpreter_args: "-u",
      cwd: __dirname,
      env: {
        PYTHONPATH: "src",
      },
      out_file: "logs/nicopush.log",
      error_file: "logs/nicopush.log",
      merge_logs: true,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      exp_backoff_restart_delay: 1000,
    },
    {
      name: "recorder",
      script: "src/cmd/recorder.py",
      interpreter: ".venv/bin/python",
      interpreter_args: "-u",
      cwd: __dirname,
      env: {
        PYTHONPATH: "src",
      },
      out_file: "logs/recorder.log",
      error_file: "logs/recorder.log",
      merge_logs: true,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      exp_backoff_restart_delay: 1000,
    },
    {
      name: "gcs_uploader",
      script: "bash",
      args: "-c 'fswatch -0 --event Created --event Renamed dist | xargs -0 -n1 .venv/bin/python -u src/cmd/upload.py'",
      interpreter: "none",
      cwd: __dirname,
      env: {
        PYTHONPATH: "src",
      },
      out_file: "logs/gcs_uploader.log",
      error_file: "logs/gcs_uploader.log",
      merge_logs: true,
      autorestart: true,
      max_restarts: 50,
      restart_delay: 5000,
      exp_backoff_restart_delay: 1000,
    },
  ],
};
